import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { gql } from "@apollo/client";
import client from "../apollo-client";

export default function Home({ accounts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://api.soundtrackyourbrand.com/v2/docs" rel="noreferrer" target="_blank">The example app!</a>
        </h1>

        <div className={styles.grid}>
          {accounts.filter(acc => acc.node != null).map((account) => (
            <div key={account.node.id} className={styles.card}>
              <h3><Link href={{
                pathname: '/account/[account]',
                query: { account: account.node.id },
              }} aria-hidden="true" class="aal_anchor" id="account-businessName">{account.node.businessName}</Link></h3>
            </div>
          ))}
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const { data, error } = await client.query({
    query: gql`
      query {
        me {
          ...on PublicAPIClient{
            accounts(first:10){
              edges{
                node{
                  id
                  businessName
                }
              }
            }
          }
        }
      }
    `,
    errorPolicy: 'all'
  });

  return {
    props: {
      accounts: data.me ? data.me.accounts.edges.filter(a => a.node !== null) : [],
    },
  };
}
